USE [ApplicationSettings]
GO

insert into ApplicationSettings.dbo.[FAPI_Import_Templates]
Select 	[Template_Name],
	[ExporterRow],
	[ExporterColumn],
	[DepartureDateRow],
	[DepartureDateColumn],
	[VesselNumberRow],
	[VesselNumberColumn],
	[VesselNameRow],
	[VesselNameColumn],
	[DestinationRow],
	[DestinationColumn],
	[PrefixRow],
	[Prefix],
	[TagNumberRow],
	[TagNumberColumn],
	[VarietyRow],
	[VarietyColumn],
	[StyleRow],
	[StyleColumn],
	[SizeRow],
	[SizeColumn],
	[GradeRow],
	[GradeColumn],
	[LabelRow],
	[LabelColumn],
	[PalletTypeRow],
	[PalletTypeCoumn],
	[InventoryQuanityRow],
	[InventoryQuantityColumn],
	[FirstPackDateRow],
	[FirstPackDateColumn],
	[GrowerNumberRow],
	[GrowerNumberColumn],
	[HatchRow] [int],
	[HatchColumn] [int],
	[DeckRow] [int],
	[DeckColumn] [int],
	[FumigatedRow] [int],
	[FumigatedColumn],
	[BillOfLadingRow],
	[BillOfLadingColumn],
	[MemoRow],
	[MemoColumn],
	[PackcodeCalculationCode],
	[VarietyTranslate],
	[StyleTranslate],
	[SizeTranslate],
	[GradeTranslate],
	[LabelTranslate],
	[ColorTranslate],
	[Other] [int],
	[Data_Sheet],
    [Data_Range],
    [Special_Processing]
FROM [dbo].[FAPI_Import_Templates_Temp]